export default [
  {
    title: "Banana bread RP",
    subTitle: "Parfait pour le petit déjeuner.",
    tags: ["Gouter", "Petit déjeuner"],
    filename: "banana-bread-rp",
  },
  {
    title: "Bretzels",
    subTitle: "Petits Pains Alsaciens",
    tags: ["Entrée", "Alsace", "Végétarien"],
    filename: "petits-pains-alsaciens",
  },
  {
    title: "Burgers",
    tags: ["Plat principal", "Américain"],
    url: "https://www.meilleurduchef.com/fr/recette/pain-burger.html",
  },
  {
    title: "Cake chorizo-maroilles",
    subTitle: "",
    tags: ["Plat principal", "Cake"],
    filename: "cake-chorizo-maroilles",
  },
  {
    title: "Cake courgette olives fêta",
    subTitle: "",
    tags: ["Plat principal", "Cake", "Sans gluten"],
    filename: "cake-courgette-olives-feta",
  },
  {
    title: "Cake noix-chèvre",
    subTitle: "",
    tags: ["Plat principal", "Cake"],
    filename: "cake-noix-chevre",
  },
  {
    title: "Cookies chocolat corn-flakes",
    subTitle: "",
    tags: ["Dessert", "Gouter", "Chocolat"],
    filename: "cookies-chocolat-corn-flakes",
  },
  {
    title: "Cookies moelleux aux pépites de chocolat",
    subTitle: "",
    tags: ["Dessert", "Gouter", "Chocolat"],
    filename: "cookies-moelleux-aux-pepites-de-chocolat",
  },
  {
    title: "Cookies RP",
    subTitle: "",
    tags: ["Dessert", "Gouter", "Chocolat"],
    filename: "cookies-rp",
  },
  {
    title: "English muffins",
    subTitle: "",
    tags: ["Plat principal"],
    filename: "english-muffins",
  },
  {
    title: "Filets de truite en papillote",
    subTitle: "",
    tags: ["Plat principal", "Poisson", "Truite"],
    filename: "filets-de-truite-en-papillote",
  },
  {
    title: "Filet mignon aux champignons et marrons",
    subTitle: "",
    tags: ["Plat principal", "Viande", "Filet mignon"],
    filename: "filet-mignon-aux-champignons-et-marrons",
  },
  {
    title: "Gnocchis",
    subTitle: "",
    tags: ["Plat principal"],
    filename: "gnocchis",
  },
  {
    title: "Lamingtons",
    subTitle: "",
    tags: ["Dessert"],
    filename: "lamingtons",
  },
  {
    title: "Pain pita",
    subTitle: "",
    tags: ["Plat principal"],
    filename: "pain-pita",
  },
  {
    title: "Pâte à crêpes",
    subTitle: "",
    tags: ["Dessert"],
    filename: "pate-a-crepes",
  },
  {
    title: "Pâte à pizza",
    subTitle: "",
    tags: ["Plat principal"],
    filename: "pate-a-pizza",
  },
  {
    title: "Rochers noix de coco",
    subTitle: "",
    tags: ["Dessert", "Goûter"],
    filename: "rochers-noix-de-coco",
  },
  {
    title: "Sauce parmesan",
    subTitle: "",
    tags: ["Accompagnement"],
    filename: "sauce-parmesan",
  },
  {
    title: "Taboulé",
    subTitle: "",
    tags: ["Plat principal"],
    filename: "taboule",
  },
];
